spring:
  application:
    name: cq-minio-starter

minio:
  access-key: MsE6HqEgzBp3klEAa74S
  secret-key: KS4DduclmvuFgAOXFu3sTl4ob5BdUE6vOnpbBAo0
  bucket-name: home-bucket
  endpoint: http://192.168.18.132:9000

